export const TOPICS = [
  { id: 'greetings', title: 'Greetings & Politeness', ru: 'Приветствия', icon: '👋', color: '#3D6C86', dialogs: [] },
  { id: 'cafes', title: 'Cafés & Restaurants', ru: 'Кафе и рестораны', icon: '☕', color: '#C17F2B', dialogs: ['coffee-formal', 'coffee-casual', 'breakfast-formal', 'breakfast-casual', 'asking-bill'] },
  { id: 'metro', title: 'Metro & Transportation', ru: 'Метро и транспорт', icon: '🚇', color: '#5C7A52', dialogs: ['buying-ticket'] },
  { id: 'hotels', title: 'Hotels & Accommodation', ru: 'Гостиницы', icon: '🛎️', color: '#8B5E83', dialogs: [] },
  { id: 'shopping', title: 'Shopping & Money', ru: 'Покупки и деньги', icon: '💶', color: '#B0562F', dialogs: ['buying-jacket'] },
  { id: 'numbers', title: 'Numbers', ru: 'Числа', icon: '#️⃣', color: '#3D6C86', dialogs: [] },
  { id: 'airport', title: 'Airport', ru: 'Аэропорт', icon: '✈️', color: '#5C7A52', dialogs: [] },
  { id: 'sightseeing', title: 'Sightseeing & Museums', ru: 'Достопримечательности', icon: '🏛️', color: '#C17F2B', dialogs: [] },
  { id: 'emergencies', title: 'Emergencies & Asking for Help', ru: 'Экстренная помощь', icon: '🆘', color: '#A6403D', dialogs: [] },
  { id: 'smalltalk', title: 'Small Talk & Everyday Conversations', ru: 'Разговоры', icon: '💬', color: '#8B5E83', dialogs: [] },
  { id: 'weather', title: 'Weather', ru: 'Погода', icon: '⛅', color: '#3D6C86', dialogs: [] },
];

export const DIALOGS = {
  'coffee-formal': {
    topicId: 'cafes', title: 'Ordering Coffee — Formal', sub: 'Waiter · You (sit-down café)',
    lines: [
      { speaker: 'Waiter', side: 'left', ru: 'Доброе утро! Что будете заказывать?', translit: 'Dobroe utro! Chto budete zakazyvat?', tr: 'Good morning! What will you be ordering?',
        words: [['Доброе', 'good'], ['утро', 'morning'], ['Что', 'what'], ['будете', 'will (you)'], ['заказывать', 'to order']] },
      { speaker: 'You', side: 'right', ru: 'Здравствуйте, можно мне капучино, пожалуйста.', translit: 'Zdravstvuyte, mozhno mne kapuchino, pozhaluysta.', tr: 'Hello, could I have a cappuccino, please.',
        words: [['Здравствуйте', 'hello (formal)'], ['можно', 'may/could'], ['мне', 'me'], ['капучино', 'cappuccino'], ['пожалуйста', 'please']] },
      { speaker: 'Waiter', side: 'left', ru: 'Конечно. Какой объём — маленький, средний или большой?', translit: 'Konechno. Kakoy obyom — malenkiy, sredniy ili bolshoy?', tr: 'Of course. What size — small, medium, or large?',
        words: [['Конечно', 'of course'], ['Какой', 'what/which'], ['объём', 'size'], ['маленький', 'small'], ['средний', 'medium'], ['большой', 'large']] },
      { speaker: 'You', side: 'right', ru: 'Средний, пожалуйста.', translit: 'Sredniy, pozhaluysta.', tr: 'Medium, please.',
        words: [['Средний', 'medium']] },
      { speaker: 'Waiter', side: 'left', ru: 'На каком молоке — обычное, овсяное, миндальное?', translit: 'Na kakom moloke — obychnoe, ovsyanoe, mindalnoe?', tr: 'What kind of milk — regular, oat, almond?',
        words: [['молоке', 'milk'], ['обычное', 'regular'], ['овсяное', 'oat'], ['миндальное', 'almond']] },
      { speaker: 'You', side: 'right', ru: 'На овсяном, если можно.', translit: 'Na ovsyanom, esli mozhno.', tr: 'Oat, if possible.',
        words: [['овсяном', 'oat'], ['если', 'if']] },
      { speaker: 'Waiter', side: 'left', ru: 'Хорошо. Что-нибудь ещё?', translit: 'Khorosho. Chto-nibud eshchyo?', tr: 'Alright. Anything else?',
        words: [['Хорошо', 'alright'], ['Что-нибудь', 'anything'], ['ещё', 'else']] },
      { speaker: 'You', side: 'right', ru: 'Нет, спасибо, это всё.', translit: 'Net, spasibo, eto vsyo.', tr: 'No thanks, that’s all.',
        words: [['Нет', 'no'], ['спасибо', 'thanks'], ['это', 'this'], ['всё', 'all']] },
      { speaker: 'Waiter', side: 'left', ru: 'Присаживайтесь, я принесу.', translit: 'Prisazhivaytes, ya prinesu.', tr: 'Have a seat, I’ll bring it over.',
        words: [['Присаживайтесь', 'have a seat'], ['принесу', 'I’ll bring']] },
    ],
  },
  'coffee-casual': {
    topicId: 'cafes', title: 'Ordering Coffee — Casual', sub: 'Barista · You (slang)',
    lines: [
      { speaker: 'Barista', side: 'left', ru: 'Привет! Что будешь?', translit: 'Privet! Chto budesh?', tr: 'Hey! What’ll you have?',
        words: [['Привет', 'hey'], ['будешь', 'will you (have)']] },
      { speaker: 'You', side: 'right', ru: 'Капучино на овсяном, среднюю.', translit: 'Kapuchino na ovsyanom, srednyuyu.', tr: 'Oat cappuccino, medium.',
        words: [['среднюю', 'medium']] },
      { speaker: 'Barista', side: 'left', ru: 'С собой или здесь?', translit: 'S soboy ili zdes?', tr: 'To go or for here?',
        words: [['С собой', 'to go'], ['здесь', 'here']] },
      { speaker: 'You', side: 'right', ru: 'С собой.', translit: 'S soboy.', tr: 'To go.', words: [] },
      { speaker: 'Barista', side: 'left', ru: 'Сколько сахара — как обычно, или без?', translit: 'Skolko sakhara — kak obychno, ili bez?', tr: 'How much sugar — usual, or none?',
        words: [['Сколько', 'how much'], ['сахара', 'sugar'], ['обычно', 'usual'], ['без', 'without']] },
      { speaker: 'You', side: 'right', ru: 'Без сахара, спасибо.', translit: 'Bez sakhara, spasibo.', tr: 'No sugar, thanks.', words: [['Без сахара', 'no sugar']] },
      { speaker: 'Barista', side: 'left', ru: 'Ок, минутка.', translit: 'Ok, minutka.', tr: 'Okay, one sec.',
        words: [['минутка', 'one moment']] },
    ],
  },
  'breakfast-formal': {
    topicId: 'cafes', title: 'Ordering Breakfast — Formal', sub: 'Waiter · You (sit-down café)',
    lines: [
      { speaker: 'Waiter', side: 'left', ru: 'Вот меню. Что-то подсказать?', translit: 'Vot menyu. Chto-to podskazat?', tr: 'Here’s the menu. Can I suggest anything?',
        words: [['Вот', 'here'], ['меню', 'menu'], ['подсказать', 'to suggest']] },
      { speaker: 'You', side: 'right', ru: 'Да, что у вас есть на завтрак?', translit: 'Da, chto u vas est na zavtrak?', tr: 'Yes, what do you have for breakfast?',
        words: [['Да', 'yes'], ['завтрак', 'breakfast']] },
      { speaker: 'Waiter', side: 'left', ru: 'У нас есть сырники, омлет, овсяная каша, тосты с авокадо и блины.', translit: 'U nas est syrniki, omlet, ovsyanaya kasha, tosty s avokado i bliny.', tr: 'We have syrniki, omelet, oatmeal, avocado toast, and bliny/pancakes.',
        words: [['сырники', 'cheese pancakes (syrniki)'], ['омлет', 'omelet'], ['каша', 'porridge'], ['тосты', 'toast'], ['авокадо', 'avocado'], ['блины', 'pancakes (bliny)']] },
      { speaker: 'You', side: 'right', ru: 'Я возьму сырники и омлет с сыром, пожалуйста.', translit: 'Ya vozmu syrniki i omlet s syrom, pozhaluysta.', tr: 'I’ll have syrniki and a cheese omelet, please.',
        words: [['возьму', 'I’ll take'], ['сыром', 'cheese']] },
      { speaker: 'Waiter', side: 'left', ru: 'Омлет из скольких яиц — двух или трёх?', translit: 'Omlet iz skolkikh yaits — dvukh ili tryokh?', tr: 'Omelet with how many eggs — two or three?',
        words: [['яиц', 'eggs'], ['двух', 'two'], ['трёх', 'three']] },
      { speaker: 'You', side: 'right', ru: 'Из двух, спасибо.', translit: 'Iz dvukh, spasibo.', tr: 'Two, thanks.', words: [] },
      { speaker: 'Waiter', side: 'left', ru: 'Что-нибудь из напитков?', translit: 'Chto-nibud iz napitkov?', tr: 'Anything to drink?',
        words: [['напитков', 'drinks']] },
      { speaker: 'You', side: 'right', ru: 'Апельсиновый сок и, пожалуйста, ещё один капучино.', translit: 'Apelsinovyy sok i, pozhaluysta, eshchyo odin kapuchino.', tr: 'Orange juice, and one more cappuccino please.',
        words: [['Апельсиновый', 'orange'], ['сок', 'juice'], ['ещё один', 'one more']] },
      { speaker: 'Waiter', side: 'left', ru: 'Отлично, сейчас всё будет.', translit: 'Otlichno, seychas vsyo budet.', tr: 'Great, coming right up.',
        words: [['Отлично', 'great'], ['сейчас', 'right now']] },
    ],
  },
  'breakfast-casual': {
    topicId: 'cafes', title: 'Ordering Breakfast — Casual', sub: 'Barista/Friend · You (slang)',
    lines: [
      { speaker: 'Barista', side: 'left', ru: 'Есть будешь что-нибудь? Или только кофе?', translit: 'Est budesh chto-nibud? Ili tolko kofe?', tr: 'You gonna eat something? Or just coffee?',
        words: [['Есть', 'to eat'], ['только', 'only']] },
      { speaker: 'You', side: 'right', ru: 'Ну давай, что посоветуешь?', translit: 'Nu davay, chto posovetuesh?', tr: 'Sure, what do you recommend?',
        words: [['давай', 'sure/go ahead'], ['посоветуешь', 'recommend']] },
      { speaker: 'Barista', side: 'left', ru: 'Сырники топовые, все берут.', translit: 'Syrniki topovye, vse berut.', tr: 'The syrniki are top-notch, everyone gets them.',
        words: [['топовые', 'top-notch'], ['все', 'everyone'], ['берут', 'get/take']] },
      { speaker: 'You', side: 'right', ru: 'Погнали, давай сырники и капучино.', translit: 'Pognali, davay syrniki i kapuchino.', tr: 'Let’s do it, syrniki and a cappuccino.',
        words: [['Погнали', 'let’s go']] },
      { speaker: 'Barista', side: 'left', ru: 'Со сметаной или с джемом?', translit: 'So smetanoy ili s dzhemom?', tr: 'With sour cream or jam?',
        words: [['сметаной', 'sour cream'], ['джемом', 'jam']] },
      { speaker: 'You', side: 'right', ru: 'Со сметаной, конечно.', translit: 'So smetanoy, konechno.', tr: 'Sour cream, of course.',
        words: [['сметаной', 'sour cream'], ['конечно', 'of course']] },
    ],
  },
  'asking-bill': {
    topicId: 'cafes', title: 'Paying the Bill', sub: 'Waiter · You (formal)',
    lines: [
      { speaker: 'You', side: 'right', ru: 'Можно счёт, пожалуйста?', translit: 'Mozhno schyot, pozhaluysta?', tr: 'Could I have the bill, please?',
        words: [['счёт', 'bill']] },
      { speaker: 'Waiter', side: 'left', ru: 'Конечно, один момент.', translit: 'Konechno, odin moment.', tr: 'Of course, one moment.',
        words: [['Конечно', 'of course'], ['момент', 'moment']] },
      { speaker: 'You', side: 'right', ru: 'Можно оплатить картой?', translit: 'Mozhno oplatit kartoy?', tr: 'Can I pay by card?',
        words: [['оплатить', 'to pay'], ['картой', 'by card']] },
      { speaker: 'Waiter', side: 'left', ru: 'Да, конечно.', translit: 'Da, konechno.', tr: 'Yes, of course.', words: [] },
      { speaker: 'You', side: 'right', ru: 'Сдачи не надо.', translit: 'Sdachi ne nado.', tr: 'Keep the change.',
        words: [['Сдачи', 'change'], ['надо', 'need/necessary']] },
    ],
  },
  'buying-jacket': {
    topicId: 'shopping', title: 'Shopping for a Jacket', sub: 'Salesperson · You (clothing shop)',
    lines: [
      { speaker: 'Salesperson', side: 'left', ru: 'Здравствуйте! Вам помочь?', tr: 'Hello! Can I help you?',
        words: [['Здравствуйте', 'hello (formal)'], ['помочь', 'to help']] },
      { speaker: 'You', side: 'right', ru: 'Здравствуйте. Да, я ищу куртку.', tr: 'Hello. Yes, I’m looking for a jacket.',
        words: [['ищу', 'looking for'], ['куртку', 'jacket']] },
      { speaker: 'Salesperson', side: 'left', ru: 'Какой размер вам нужен?', tr: 'What size do you need?',
        words: [['размер', 'size'], ['нужен', 'need']] },
      { speaker: 'You', side: 'right', ru: 'Мне нужен размер M.', tr: 'I need size M.',
        words: [['Мне', 'me'], ['нужен', 'need']] },
      { speaker: 'Salesperson', side: 'left', ru: 'Вот, пожалуйста. Примерьте.', tr: 'Here you go. Try it on.',
        words: [['Вот', 'here'], ['пожалуйста', 'please'], ['Примерьте', 'try it on']] },
      { speaker: 'You', side: 'right', ru: 'Спасибо. А сколько это стоит?', tr: 'Thanks. And how much does it cost?',
        words: [['Спасибо', 'thanks'], ['сколько', 'how much'], ['стоит', 'costs']] },
      { speaker: 'Salesperson', side: 'left', ru: 'Это стоит три тысячи рублей.', tr: 'It costs three thousand rubles.',
        words: [['стоит', 'costs'], ['три тысячи', 'three thousand'], ['рублей', 'rubles']] },
      { speaker: 'You', side: 'right', ru: 'А есть подешевле?', tr: 'Is there something cheaper?',
        words: [['есть', 'is there'], ['подешевле', 'cheaper']] },
      { speaker: 'Salesperson', side: 'left', ru: 'Да, вот эта модель стоит две тысячи пятьсот рублей.', tr: 'Yes, this model costs two thousand five hundred rubles.',
        words: [['модель', 'model'], ['две тысячи пятьсот', 'two thousand five hundred'], ['рублей', 'rubles']] },
      { speaker: 'You', side: 'right', ru: 'Можно посмотреть другой цвет?', tr: 'Can I see another color?',
        words: [['Можно', 'may/can'], ['посмотреть', 'to see'], ['другой', 'another'], ['цвет', 'color']] },
      { speaker: 'Salesperson', side: 'left', ru: 'Конечно. Какой цвет вы хотите?', tr: 'Of course. What color would you like?',
        words: [['Конечно', 'of course'], ['цвет', 'color'], ['хотите', 'want']] },
      { speaker: 'You', side: 'right', ru: 'Чёрный, пожалуйста.', tr: 'Black, please.',
        words: [['Чёрный', 'black']] },
      { speaker: 'Salesperson', side: 'left', ru: 'Вот чёрный.', tr: 'Here’s the black one.',
        words: [['чёрный', 'black']] },
      { speaker: 'You', side: 'right', ru: 'Можно примерить?', tr: 'Can I try it on?',
        words: [['примерить', 'to try on']] },
      { speaker: 'Salesperson', side: 'left', ru: 'Конечно.', tr: 'Of course.', words: [] },
      { speaker: 'You', side: 'right', ru: 'Мне нравится. Но дороговато.', tr: 'I like it. But it’s a bit expensive.',
        words: [['нравится', 'like'], ['дороговато', 'a bit expensive']] },
      { speaker: 'Salesperson', side: 'left', ru: 'У нас сейчас скидка. Цена — две тысячи рублей.', tr: 'We have a discount right now. The price is two thousand rubles.',
        words: [['скидка', 'discount'], ['Цена', 'price'], ['две тысячи', 'two thousand']] },
      { speaker: 'You', side: 'right', ru: 'Хорошо, я возьму.', tr: 'Okay, I’ll take it.',
        words: [['Хорошо', 'okay'], ['возьму', 'I’ll take']] },
      { speaker: 'Salesperson', side: 'left', ru: 'Вам пакет нужен?', tr: 'Do you need a bag?',
        words: [['пакет', 'bag']] },
      { speaker: 'You', side: 'right', ru: 'Да, пожалуйста.', tr: 'Yes, please.', words: [] },
      { speaker: 'Salesperson', side: 'left', ru: 'С вас две тысячи рублей.', tr: 'That’ll be two thousand rubles.',
        words: [['С вас', 'from you'], ['две тысячи', 'two thousand']] },
      { speaker: 'You', side: 'right', ru: 'Можно картой?', tr: 'Can I pay by card?',
        words: [['картой', 'by card']] },
      { speaker: 'Salesperson', side: 'left', ru: 'Да, конечно.', tr: 'Yes, of course.', words: [] },
      { speaker: 'You', side: 'right', ru: 'Спасибо!', tr: 'Thank you!',
        words: [['Спасибо', 'thanks']] },
    ],
  },
  'buying-ticket': {
    topicId: 'metro', title: 'Buying a Metro Ticket', sub: 'Cashier · Traveler',
    lines: [
      { speaker: 'Traveler', side: 'right', ru: 'Здравствуйте, один билет до центра, пожалуйста.', tr: 'Hello, one ticket to the center, please.',
        words: [['один', 'one'], ['билет', 'ticket'], ['до', 'to'], ['центра', 'the center'], ['пожалуйста', 'please']] },
      { speaker: 'Cashier', side: 'left', ru: 'На одну поездку или проездной?', tr: 'For one ride, or a travel pass?',
        words: [['одну', 'one'], ['поездку', 'ride'], ['или', 'or'], ['проездной', 'travel pass']] },
      { speaker: 'Traveler', side: 'right', ru: 'На одну поездку.', tr: 'For one ride.', words: [] },
      { speaker: 'Cashier', side: 'left', ru: 'С вас пятьдесят рублей.', tr: 'That will be fifty rubles.',
        words: [['С вас', 'from you (i.e. you owe)'], ['пятьдесят', 'fifty'], ['рублей', 'rubles']] },
    ],
  },
};

export const INITIAL_FLASHCARDS = [
  { word: 'капучино', tr: 'cappuccino', dialogId: 'coffee-formal', topicId: 'cafes' },
  { word: 'пожалуйста', tr: 'please', dialogId: 'coffee-formal', topicId: 'cafes' },
  { word: 'билет', tr: 'ticket', dialogId: 'buying-ticket', topicId: 'metro' },
  { word: 'счёт', tr: 'bill', dialogId: 'asking-bill', topicId: 'cafes' },
  { word: 'сырники', tr: 'cheese pancakes (syrniki)', dialogId: 'breakfast-formal', topicId: 'cafes' },
  { word: 'омлет', tr: 'omelet', dialogId: 'breakfast-formal', topicId: 'cafes' },
  { word: 'каша', tr: 'porridge', dialogId: 'breakfast-formal', topicId: 'cafes' },
  { word: 'сметаной', tr: 'sour cream', dialogId: 'breakfast-casual', topicId: 'cafes' },
];
