export const TOPICS = [
  { id: 'greetings', title: 'Greetings & Politeness', ru: 'Приветствия', icon: '👋', color: '#3D6C86', dialogs: [] },
  { id: 'cafes', title: 'Cafés & Restaurants', ru: 'Кафе и рестораны', icon: '☕', color: '#C17F2B', dialogs: ['coffee-formal', 'coffee-casual', 'breakfast-formal', 'breakfast-casual', 'asking-bill'] },
  { id: 'metro', title: 'Metro & Transportation', ru: 'Метро и транспорт', icon: '🚇', color: '#5C7A52', dialogs: ['buying-ticket'] },
  { id: 'hotels', title: 'Hotels & Accommodation', ru: 'Гостиницы', icon: '🛎️', color: '#8B5E83', dialogs: [] },
  { id: 'shopping', title: 'Shopping & Money', ru: 'Покупки и деньги', icon: '💶', color: '#B0562F', dialogs: ['buying-jacket', 'buying-shoes', 'supermarket-shopping', 'buying-by-weight', 'buying-souvenirs', 'return-exchange', 'seller-speaks-fast'] },
  { id: 'numbers', title: 'Numbers', ru: 'Числа', icon: '#️⃣', color: '#3D6C86', dialogs: [] },
  { id: 'airport', title: 'Airport', ru: 'Аэропорт', icon: '✈️', color: '#5C7A52', dialogs: ['airport-checkin', 'airport-finding-gate', 'airport-passport-control', 'airport-security-check'] },
  { id: 'sightseeing', title: 'Sightseeing & Museums', ru: 'Достопримечательности', icon: '🏛️', color: '#C17F2B', dialogs: [] },
  { id: 'emergencies', title: 'Emergencies & Asking for Help', ru: 'Экстренная помощь', icon: '🆘', color: '#A6403D', dialogs: [] },
  { id: 'smalltalk', title: 'Small Talk & Everyday Conversations', ru: 'Разговоры', icon: '💬', color: '#8B5E83', dialogs: [] },
  { id: 'weather', title: 'Weather', ru: 'Погода', icon: '⛅', color: '#3D6C86', dialogs: ['weather-smalltalk', 'weather-rain', 'weather-snow', 'weather-temperature', 'weather-wind', 'weather-cloudy', 'weather-changing', 'weather-forecast', 'weather-what-to-wear', 'weather-yesterday-today', 'weather-seasons', 'weather-asking-stranger'] },
  { id: 'banksim', title: 'Bank & SIM', ru: 'Банк и SIM-карта', icon: '💳', color: '#2F7A6E', dialogs: ['opening-bank-card', 'atm-withdraw', 'paying-card', 'buying-esim', 'activating-esim', 'airport-wifi', 'internet-not-working'] },
];

export const DIALOGS = {
  'coffee-formal': {
    topicId: 'cafes', title: 'Ordering Coffee — Formal', sub: 'Waiter · You (sit-down café)',
    lines: [
      { speaker: 'Waiter', side: 'left', ru: 'Доброе утро! Что будете заказывать?', translit: 'Dobroe utro! Chto budete zakazyvat?', tr: 'Good morning! What will you be ordering?',
        words: [['Доброе', 'good'], ['утро', 'morning'], ['Что', 'what'], ['будете', 'will (you)'], ['заказывать', 'to order']] },
      { speaker: 'You', side: 'right', ru: 'Здравствуйте, можно мне капучино, пожалуйста.', translit: 'Zdravstvuyte, mozhno mne kapuchino, pozhaluysta.', tr: 'Hello, could I have a cappuccino, please.',
        words: [['Здравствуйте', 'hello (formal)'], ['можно', 'may/could'], ['мне', 'me'], ['капучино', 'cappuccino'], ['пожалуйста', 'please']] },
      { speaker: 'Waiter', side: 'left', ru: 'Конечно. Какой объём — маленький, средний или большой?', translit: 'Konechno. Kakoy obyom — malenkiy, sredniy ili bolshoy?', tr: 'Of course. What size — small, medium, or large?',
        words: [['Конечно', 'of course'], ['Какой', 'what/which'], ['объём', 'size'], ['маленький', 'small'], ['средний', 'medium'], ['большой', 'large']] },
      { speaker: 'You', side: 'right', ru: 'Средний, пожалуйста.', translit: 'Sredniy, pozhaluysta.', tr: 'Medium, please.',
        words: [['Средний', 'medium']] },
      { speaker: 'Waiter', side: 'left', ru: 'На каком молоке — обычное, овсяное, миндальное?', translit: 'Na kakom moloke — obychnoe, ovsyanoe, mindalnoe?', tr: 'What kind of milk — regular, oat, almond?',
        words: [['молоке', 'milk'], ['обычное', 'regular'], ['овсяное', 'oat'], ['миндальное', 'almond']] },
      { speaker: 'You', side: 'right', ru: 'На овсяном, если можно.', translit: 'Na ovsyanom, esli mozhno.', tr: 'Oat, if possible.',
        words: [['овсяном', 'oat'], ['если', 'if']] },
      { speaker: 'Waiter', side: 'left', ru: 'Хорошо. Что-нибудь ещё?', translit: 'Khorosho. Chto-nibud eshchyo?', tr: 'Alright. Anything else?',
        words: [['Хорошо', 'alright'], ['Что-нибудь', 'anything'], ['ещё', 'else']] },
      { speaker: 'You', side: 'right', ru: 'Нет, спасибо, это всё.', translit: 'Net, spasibo, eto vsyo.', tr: 'No thanks, that’s all.',
        words: [['Нет', 'no'], ['спасибо', 'thanks'], ['это', 'this'], ['всё', 'all']] },
      { speaker: 'Waiter', side: 'left', ru: 'Присаживайтесь, я принесу.', translit: 'Prisazhivaytes, ya prinesu.', tr: 'Have a seat, I’ll bring it over.',
        words: [['Присаживайтесь', 'have a seat'], ['принесу', 'I’ll bring']] },
    ],
  },
  'coffee-casual': {
    topicId: 'cafes', title: 'Ordering Coffee — Casual', sub: 'Barista · You (slang)',
    lines: [
      { speaker: 'Barista', side: 'left', ru: 'Привет! Что будешь?', translit: 'Privet! Chto budesh?', tr: 'Hey! What’ll you have?',
        words: [['Привет', 'hey'], ['будешь', 'will you (have)']] },
      { speaker: 'You', side: 'right', ru: 'Капучино на овсяном, среднюю.', translit: 'Kapuchino na ovsyanom, srednyuyu.', tr: 'Oat cappuccino, medium.',
        words: [['среднюю', 'medium']] },
      { speaker: 'Barista', side: 'left', ru: 'С собой или здесь?', translit: 'S soboy ili zdes?', tr: 'To go or for here?',
        words: [['С собой', 'to go'], ['здесь', 'here']] },
      { speaker: 'You', side: 'right', ru: 'С собой.', translit: 'S soboy.', tr: 'To go.', words: [] },
      { speaker: 'Barista', side: 'left', ru: 'Сколько сахара — как обычно, или без?', translit: 'Skolko sakhara — kak obychno, ili bez?', tr: 'How much sugar — usual, or none?',
        words: [['Сколько', 'how much'], ['сахара', 'sugar'], ['обычно', 'usual'], ['без', 'without']] },
      { speaker: 'You', side: 'right', ru: 'Без сахара, спасибо.', translit: 'Bez sakhara, spasibo.', tr: 'No sugar, thanks.', words: [['Без сахара', 'no sugar']] },
      { speaker: 'Barista', side: 'left', ru: 'Ок, минутка.', translit: 'Ok, minutka.', tr: 'Okay, one sec.',
        words: [['минутка', 'one moment']] },
    ],
  },
  'breakfast-formal': {
    topicId: 'cafes', title: 'Ordering Breakfast — Formal', sub: 'Waiter · You (sit-down café)',
    lines: [
      { speaker: 'Waiter', side: 'left', ru: 'Вот меню. Что-то подсказать?', translit: 'Vot menyu. Chto-to podskazat?', tr: 'Here’s the menu. Can I suggest anything?',
        words: [['Вот', 'here'], ['меню', 'menu'], ['подсказать', 'to suggest']] },
      { speaker: 'You', side: 'right', ru: 'Да, что у вас есть на завтрак?', translit: 'Da, chto u vas est na zavtrak?', tr: 'Yes, what do you have for breakfast?',
        words: [['Да', 'yes'], ['завтрак', 'breakfast']] },
      { speaker: 'Waiter', side: 'left', ru: 'У нас есть сырники, омлет, овсяная каша, тосты с авокадо и блины.', translit: 'U nas est syrniki, omlet, ovsyanaya kasha, tosty s avokado i bliny.', tr: 'We have syrniki, omelet, oatmeal, avocado toast, and bliny/pancakes.',
        words: [['сырники', 'cheese pancakes (syrniki)'], ['омлет', 'omelet'], ['каша', 'porridge'], ['тосты', 'toast'], ['авокадо', 'avocado'], ['блины', 'pancakes (bliny)']] },
      { speaker: 'You', side: 'right', ru: 'Я возьму сырники и омлет с сыром, пожалуйста.', translit: 'Ya vozmu syrniki i omlet s syrom, pozhaluysta.', tr: 'I’ll have syrniki and a cheese omelet, please.',
        words: [['возьму', 'I’ll take'], ['сыром', 'cheese']] },
      { speaker: 'Waiter', side: 'left', ru: 'Омлет из скольких яиц — двух или трёх?', translit: 'Omlet iz skolkikh yaits — dvukh ili tryokh?', tr: 'Omelet with how many eggs — two or three?',
        words: [['яиц', 'eggs'], ['двух', 'two'], ['трёх', 'three']] },
      { speaker: 'You', side: 'right', ru: 'Из двух, спасибо.', translit: 'Iz dvukh, spasibo.', tr: 'Two, thanks.', words: [] },
      { speaker: 'Waiter', side: 'left', ru: 'Что-нибудь из напитков?', translit: 'Chto-nibud iz napitkov?', tr: 'Anything to drink?',
        words: [['напитков', 'drinks']] },
      { speaker: 'You', side: 'right', ru: 'Апельсиновый сок и, пожалуйста, ещё один капучино.', translit: 'Apelsinovyy sok i, pozhaluysta, eshchyo odin kapuchino.', tr: 'Orange juice, and one more cappuccino please.',
        words: [['Апельсиновый', 'orange'], ['сок', 'juice'], ['ещё один', 'one more']] },
      { speaker: 'Waiter', side: 'left', ru: 'Отлично, сейчас всё будет.', translit: 'Otlichno, seychas vsyo budet.', tr: 'Great, coming right up.',
        words: [['Отлично', 'great'], ['сейчас', 'right now']] },
    ],
  },
  'breakfast-casual': {
    topicId: 'cafes', title: 'Ordering Breakfast — Casual', sub: 'Barista/Friend · You (slang)',
    lines: [
      { speaker: 'Barista', side: 'left', ru: 'Есть будешь что-нибудь? Или только кофе?', translit: 'Est budesh chto-nibud? Ili tolko kofe?', tr: 'You gonna eat something? Or just coffee?',
        words: [['Есть', 'to eat'], ['только', 'only']] },
      { speaker: 'You', side: 'right', ru: 'Ну давай, что посоветуешь?', translit: 'Nu davay, chto posovetuesh?', tr: 'Sure, what do you recommend?',
        words: [['давай', 'sure/go ahead'], ['посоветуешь', 'recommend']] },
      { speaker: 'Barista', side: 'left', ru: 'Сырники топовые, все берут.', translit: 'Syrniki topovye, vse berut.', tr: 'The syrniki are top-notch, everyone gets them.',
        words: [['топовые', 'top-notch'], ['все', 'everyone'], ['берут', 'get/take']] },
      { speaker: 'You', side: 'right', ru: 'Погнали, давай сырники и капучино.', translit: 'Pognali, davay syrniki i kapuchino.', tr: 'Let’s do it, syrniki and a cappuccino.',
        words: [['Погнали', 'let’s go']] },
      { speaker: 'Barista', side: 'left', ru: 'Со сметаной или с джемом?', translit: 'So smetanoy ili s dzhemom?', tr: 'With sour cream or jam?',
        words: [['сметаной', 'sour cream'], ['джемом', 'jam']] },
      { speaker: 'You', side: 'right', ru: 'Со сметаной, конечно.', translit: 'So smetanoy, konechno.', tr: 'Sour cream, of course.',
        words: [['сметаной', 'sour cream'], ['конечно', 'of course']] },
    ],
  },
  'asking-bill': {
    topicId: 'cafes', title: 'Paying the Bill', sub: 'Waiter · You (formal)',
    lines: [
      { speaker: 'You', side: 'right', ru: 'Можно счёт, пожалуйста?', translit: 'Mozhno schyot, pozhaluysta?', tr: 'Could I have the bill, please?',
        words: [['счёт', 'bill']] },
      { speaker: 'Waiter', side: 'left', ru: 'Конечно, один момент.', translit: 'Konechno, odin moment.', tr: 'Of course, one moment.',
        words: [['Конечно', 'of course'], ['момент', 'moment']] },
      { speaker: 'You', side: 'right', ru: 'Можно оплатить картой?', translit: 'Mozhno oplatit kartoy?', tr: 'Can I pay by card?',
        words: [['оплатить', 'to pay'], ['картой', 'by card']] },
      { speaker: 'Waiter', side: 'left', ru: 'Да, конечно.', translit: 'Da, konechno.', tr: 'Yes, of course.', words: [] },
      { speaker: 'You', side: 'right', ru: 'Сдачи не надо.', translit: 'Sdachi ne nado.', tr: 'Keep the change.',
        words: [['Сдачи', 'change'], ['надо', 'need/necessary']] },
    ],
  },
  'buying-jacket': {
    topicId: 'shopping', title: 'Shopping for a Jacket', sub: 'Salesperson · You (clothing shop)',
    lines: [
      { speaker: 'Salesperson', side: 'left', ru: 'Здравствуйте! Вам помочь?', tr: 'Hello! Can I help you?',
        words: [['Здравствуйте', 'hello (formal)'], ['помочь', 'to help']] },
      { speaker: 'You', side: 'right', ru: 'Здравствуйте. Да, я ищу куртку.', tr: 'Hello. Yes, I’m looking for a jacket.',
        words: [['ищу', 'looking for'], ['куртку', 'jacket']] },
      { speaker: 'Salesperson', side: 'left', ru: 'Какой размер вам нужен?', tr: 'What size do you need?',
        words: [['размер', 'size'], ['нужен', 'need']] },
      { speaker: 'You', side: 'right', ru: 'Мне нужен размер M.', tr: 'I need size M.',
        words: [['Мне', 'me'], ['нужен', 'need']] },
      { speaker: 'Salesperson', side: 'left', ru: 'Вот, пожалуйста. Примерьте.', tr: 'Here you go. Try it on.',
        words: [['Вот', 'here'], ['пожалуйста', 'please'], ['Примерьте', 'try it on']] },
      { speaker: 'You', side: 'right', ru: 'Спасибо. А сколько это стоит?', tr: 'Thanks. And how much does it cost?',
        words: [['Спасибо', 'thanks'], ['сколько', 'how much'], ['стоит', 'costs']] },
      { speaker: 'Salesperson', side: 'left', ru: 'Это стоит три тысячи рублей.', tr: 'It costs three thousand rubles.',
        words: [['стоит', 'costs'], ['три тысячи', 'three thousand'], ['рублей', 'rubles']] },
      { speaker: 'You', side: 'right', ru: 'А есть подешевле?', tr: 'Is there something cheaper?',
        words: [['есть', 'is there'], ['подешевле', 'cheaper']] },
      { speaker: 'Salesperson', side: 'left', ru: 'Да, вот эта модель стоит две тысячи пятьсот рублей.', tr: 'Yes, this model costs two thousand five hundred rubles.',
        words: [['модель', 'model'], ['две тысячи пятьсот', 'two thousand five hundred'], ['рублей', 'rubles']] },
      { speaker: 'You', side: 'right', ru: 'Можно посмотреть другой цвет?', tr: 'Can I see another color?',
        words: [['Можно', 'may/can'], ['посмотреть', 'to see'], ['другой', 'another'], ['цвет', 'color']] },
      { speaker: 'Salesperson', side: 'left', ru: 'Конечно. Какой цвет вы хотите?', tr: 'Of course. What color would you like?',
        words: [['Конечно', 'of course'], ['цвет', 'color'], ['хотите', 'want']] },
      { speaker: 'You', side: 'right', ru: 'Чёрный, пожалуйста.', tr: 'Black, please.',
        words: [['Чёрный', 'black']] },
      { speaker: 'Salesperson', side: 'left', ru: 'Вот чёрный.', tr: 'Here’s the black one.',
        words: [['чёрный', 'black']] },
      { speaker: 'You', side: 'right', ru: 'Можно примерить?', tr: 'Can I try it on?',
        words: [['примерить', 'to try on']] },
      { speaker: 'Salesperson', side: 'left', ru: 'Конечно.', tr: 'Of course.', words: [] },
      { speaker: 'You', side: 'right', ru: 'Мне нравится. Но дороговато.', tr: 'I like it. But it’s a bit expensive.',
        words: [['нравится', 'like'], ['дороговато', 'a bit expensive']] },
      { speaker: 'Salesperson', side: 'left', ru: 'У нас сейчас скидка. Цена — две тысячи рублей.', tr: 'We have a discount right now. The price is two thousand rubles.',
        words: [['скидка', 'discount'], ['Цена', 'price'], ['две тысячи', 'two thousand']] },
      { speaker: 'You', side: 'right', ru: 'Хорошо, я возьму.', tr: 'Okay, I’ll take it.',
        words: [['Хорошо', 'okay'], ['возьму', 'I’ll take']] },
      { speaker: 'Salesperson', side: 'left', ru: 'Вам пакет нужен?', tr: 'Do you need a bag?',
        words: [['пакет', 'bag']] },
      { speaker: 'You', side: 'right', ru: 'Да, пожалуйста.', tr: 'Yes, please.', words: [] },
      { speaker: 'Salesperson', side: 'left', ru: 'С вас две тысячи рублей.', tr: 'That’ll be two thousand rubles.',
        words: [['С вас', 'from you'], ['две тысячи', 'two thousand']] },
      { speaker: 'You', side: 'right', ru: 'Можно картой?', tr: 'Can I pay by card?',
        words: [['картой', 'by card']] },
      { speaker: 'Salesperson', side: 'left', ru: 'Да, конечно.', tr: 'Yes, of course.', words: [] },
      { speaker: 'You', side: 'right', ru: 'Спасибо!', tr: 'Thank you!',
        words: [['Спасибо', 'thanks']] },
    ],
  },
  'buying-shoes': {
    topicId: 'shopping', title: 'Shopping for Shoes', sub: 'Salesperson · You (shoe shop)',
    lines: [
      { speaker: 'Salesperson', side: 'left', ru: 'Здравствуйте! Вам помочь?', tr: 'Hello! Can I help you?',
        words: [['Здравствуйте', 'hello (formal)'], ['помочь', 'to help']] },
      { speaker: 'You', side: 'right', ru: 'Да. Я ищу кроссовки.', tr: 'Yes. I’m looking for sneakers.',
        words: [['ищу', 'looking for'], ['кроссовки', 'sneakers']] },
      { speaker: 'Salesperson', side: 'left', ru: 'Какой размер вам нужен?', tr: 'What size do you need?',
        words: [['размер', 'size'], ['нужен', 'need']] },
      { speaker: 'You', side: 'right', ru: 'Размер 38, пожалуйста.', tr: 'Size 38, please.',
        words: [['Размер', 'size'], ['пожалуйста', 'please']] },
      { speaker: 'Salesperson', side: 'left', ru: 'Вот эти. Примерьте.', tr: 'These ones. Try them on.',
        words: [['Вот', 'here'], ['Примерьте', 'try them on']] },
      { speaker: 'You', side: 'right', ru: 'Мне немного тесно.', tr: 'They’re a little tight.',
        words: [['немного', 'a little'], ['тесно', 'tight']] },
      { speaker: 'You', side: 'right', ru: 'Есть на размер больше?', tr: 'Is there one size bigger?',
        words: [['Есть', 'is there'], ['больше', 'bigger']] },
      { speaker: 'Salesperson', side: 'left', ru: 'Да, вот 39-й размер.', tr: 'Yes, here’s size 39.',
        words: [['вот', 'here'], ['размер', 'size']] },
      { speaker: 'You', side: 'right', ru: 'Спасибо. Этот размер подходит.', tr: 'Thank you. This size fits.',
        words: [['Спасибо', 'thanks'], ['подходит', 'fits']] },
      { speaker: 'You', side: 'right', ru: 'Сколько они стоят?', tr: 'How much are they?',
        words: [['Сколько', 'how much'], ['стоят', 'cost']] },
      { speaker: 'Salesperson', side: 'left', ru: 'Четыре тысячи рублей.', tr: '4,000 rubles.',
        words: [['Четыре тысячи', 'four thousand'], ['рублей', 'rubles']] },
      { speaker: 'You', side: 'right', ru: 'Хорошо, я возьму.', tr: 'Okay, I’ll take them.',
        words: [['Хорошо', 'okay'], ['возьму', 'I’ll take']] },
    ],
  },
  'supermarket-shopping': {
    topicId: 'shopping', title: 'Shopping at the Supermarket', sub: 'Employee/Cashier · You (supermarket)',
    lines: [
      { speaker: 'You', side: 'right', ru: 'Извините, где здесь молоко?', tr: 'Excuse me, where is the milk?',
        words: [['Извините', 'excuse me'], ['где', 'where'], ['молоко', 'milk']] },
      { speaker: 'Employee', side: 'left', ru: 'Молоко вон там, справа.', tr: 'The milk is over there, on the right.',
        words: [['вон там', 'over there'], ['справа', 'on the right']] },
      { speaker: 'You', side: 'right', ru: 'Спасибо. А где сыр?', tr: 'Thank you. And where is the cheese?',
        words: [['Спасибо', 'thanks'], ['сыр', 'cheese']] },
      { speaker: 'Employee', side: 'left', ru: 'На втором этаже.', tr: 'On the second floor.',
        words: [['втором', 'second'], ['этаже', 'floor']] },
      { speaker: 'You', side: 'right', ru: 'Сколько стоит этот сыр?', tr: 'How much does this cheese cost?',
        words: [['Сколько', 'how much'], ['стоит', 'costs']] },
      { speaker: 'Employee', side: 'left', ru: 'Пятьсот рублей.', tr: '500 rubles.',
        words: [['Пятьсот', 'five hundred'], ['рублей', 'rubles']] },
      { speaker: 'Cashier', side: 'left', ru: 'Картой или наличными?', tr: 'By card or cash?',
        words: [['Картой', 'by card'], ['наличными', 'cash']] },
      { speaker: 'You', side: 'right', ru: 'Картой, пожалуйста.', tr: 'By card, please.',
        words: [['Картой', 'by card'], ['пожалуйста', 'please']] },
      { speaker: 'Cashier', side: 'left', ru: 'Пакет нужен?', tr: 'Do you need a bag?',
        words: [['Пакет', 'bag'], ['нужен', 'need']] },
      { speaker: 'You', side: 'right', ru: 'Да, пожалуйста.', tr: 'Yes, please.', words: [] },
      { speaker: 'Cashier', side: 'left', ru: 'Чек нужен?', tr: 'Do you need a receipt?',
        words: [['Чек', 'receipt']] },
      { speaker: 'You', side: 'right', ru: 'Да, спасибо.', tr: 'Yes, thank you.', words: [] },
    ],
  },
  'buying-by-weight': {
    topicId: 'shopping', title: 'Buying by Weight at the Market', sub: 'Salesperson · You (market)',
    lines: [
      { speaker: 'You', side: 'right', ru: 'Здравствуйте. Мне 300 граммов сыра, пожалуйста.', tr: 'Hello. 300 grams of cheese, please.',
        words: [['Здравствуйте', 'hello (formal)'], ['граммов', 'grams'], ['сыра', 'cheese']] },
      { speaker: 'Salesperson', side: 'left', ru: 'Конечно. Что-нибудь ещё?', tr: 'Of course. Anything else?',
        words: [['Конечно', 'of course'], ['Что-нибудь', 'anything'], ['ещё', 'else']] },
      { speaker: 'You', side: 'right', ru: 'Да, мне полкило яблок.', tr: 'Yes, half a kilo of apples.',
        words: [['полкило', 'half a kilo'], ['яблок', 'apples']] },
      { speaker: 'Salesperson', side: 'left', ru: 'Хорошо. Ещё что-нибудь?', tr: 'Okay. Anything else?',
        words: [['Хорошо', 'okay'], ['Ещё', 'else']] },
      { speaker: 'You', side: 'right', ru: 'Нет, спасибо. Сколько с меня?', tr: 'No, thank you. How much do I owe you?',
        words: [['Нет', 'no'], ['Сколько с меня', 'how much do I owe you']] },
      { speaker: 'Salesperson', side: 'left', ru: 'Восемьсот рублей.', tr: '800 rubles.',
        words: [['Восемьсот', 'eight hundred'], ['рублей', 'rubles']] },
      { speaker: 'You', side: 'right', ru: 'Вот, пожалуйста.', tr: 'Here you are.',
        words: [['Вот', 'here'], ['пожалуйста', 'please']] },
    ],
  },
  'buying-souvenirs': {
    topicId: 'shopping', title: 'Buying Souvenirs', sub: 'Salesperson · You (souvenir shop)',
    lines: [
      { speaker: 'You', side: 'right', ru: 'Здравствуйте. Это местное?', tr: 'Hello. Is this local?',
        words: [['местное', 'local']] },
      { speaker: 'Salesperson', side: 'left', ru: 'Да, это сделано в Санкт-Петербурге.', tr: 'Yes, it’s made in Saint Petersburg.',
        words: [['сделано', 'made'], ['Санкт-Петербурге', 'Saint Petersburg']] },
      { speaker: 'You', side: 'right', ru: 'А это ручная работа?', tr: 'And is this handmade?',
        words: [['ручная работа', 'handmade']] },
      { speaker: 'Salesperson', side: 'left', ru: 'Да.', tr: 'Yes.', words: [] },
      { speaker: 'You', side: 'right', ru: 'Сколько это стоит?', tr: 'How much does this cost?',
        words: [['Сколько', 'how much'], ['стоит', 'costs']] },
      { speaker: 'Salesperson', side: 'left', ru: 'Тысяча рублей.', tr: '1,000 rubles.',
        words: [['Тысяча', 'one thousand'], ['рублей', 'rubles']] },
      { speaker: 'You', side: 'right', ru: 'У вас есть что-нибудь маленькое?', tr: 'Do you have something small?',
        words: [['есть', 'is there'], ['маленькое', 'small']] },
      { speaker: 'Salesperson', side: 'left', ru: 'Да, вот эти магниты.', tr: 'Yes, these magnets.',
        words: [['магниты', 'magnets']] },
      { speaker: 'You', side: 'right', ru: 'Хорошо. Я возьму два.', tr: 'Okay. I’ll take two.',
        words: [['Хорошо', 'okay'], ['возьму', 'I’ll take'], ['два', 'two']] },
      { speaker: 'You', side: 'right', ru: 'Это можно взять в ручную кладь?', tr: 'Can I take this in my carry-on luggage?',
        words: [['ручную кладь', 'carry-on luggage']] },
      { speaker: 'Salesperson', side: 'left', ru: 'Да, конечно.', tr: 'Yes, of course.', words: [] },
    ],
  },
  'return-exchange': {
    topicId: 'shopping', title: 'Returning or Exchanging an Item', sub: 'Salesperson · You (clothing shop)',
    lines: [
      { speaker: 'You', side: 'right', ru: 'Здравствуйте. Я хочу вернуть эту вещь.', tr: 'Hello. I want to return this item.',
        words: [['хочу', 'want'], ['вернуть', 'to return'], ['вещь', 'item']] },
      { speaker: 'Salesperson', side: 'left', ru: 'А что случилось?', tr: 'What happened?',
        words: [['случилось', 'happened']] },
      { speaker: 'You', side: 'right', ru: 'Размер не подходит.', tr: 'The size doesn’t fit.',
        words: [['подходит', 'fits']] },
      { speaker: 'Salesperson', side: 'left', ru: 'Вы хотите обменять её?', tr: 'Would you like to exchange it?',
        words: [['обменять', 'to exchange']] },
      { speaker: 'You', side: 'right', ru: 'Да. Есть размер побольше?', tr: 'Yes. Is there a bigger size?',
        words: [['побольше', 'bigger']] },
      { speaker: 'Salesperson', side: 'left', ru: 'Да, есть размер L.', tr: 'Yes, there is size L.', words: [] },
      { speaker: 'You', side: 'right', ru: 'Хорошо, я хочу обменять.', tr: 'Okay, I want to exchange it.',
        words: [['Хорошо', 'okay'], ['обменять', 'to exchange']] },
    ],
  },
  'seller-speaks-fast': {
    topicId: 'shopping', title: 'When the Seller Speaks Too Fast', sub: 'Salesperson · You',
    lines: [
      { speaker: 'Salesperson', side: 'left', ru: 'Быстрая фраза на русском…', tr: 'A fast sentence in Russian…',
        words: [['Быстрая', 'fast'], ['фраза', 'sentence']] },
      { speaker: 'You', side: 'right', ru: 'Извините, я не поняла. Можно ещё раз, пожалуйста?', tr: 'Sorry, I didn’t understand. Could you say it again, please?',
        words: [['Извините', 'sorry/excuse me'], ['поняла', 'understood (female)'], ['ещё раз', 'again']] },
      { speaker: 'Salesperson', side: 'left', ru: 'Конечно.', tr: 'Of course.', words: [] },
      { speaker: 'You', side: 'right', ru: 'Можете говорить помедленнее, пожалуйста?', tr: 'Could you speak more slowly, please?',
        words: [['говорить', 'to speak'], ['помедленнее', 'more slowly']] },
      { speaker: 'Salesperson', side: 'left', ru: 'Да, конечно.', tr: 'Yes, of course.', words: [] },
      { speaker: 'You', side: 'right', ru: 'Я немного говорю по-русски.', tr: 'I speak a little Russian.',
        words: [['немного', 'a little'], ['говорю', 'I speak'], ['по-русски', 'in Russian']] },
    ],
  },
  'buying-ticket': {
    topicId: 'metro', title: 'Buying a Metro Ticket', sub: 'Cashier · Traveler',
    lines: [
      { speaker: 'Traveler', side: 'right', ru: 'Здравствуйте, один билет до центра, пожалуйста.', tr: 'Hello, one ticket to the center, please.',
        words: [['один', 'one'], ['билет', 'ticket'], ['до', 'to'], ['центра', 'the center'], ['пожалуйста', 'please']] },
      { speaker: 'Cashier', side: 'left', ru: 'На одну поездку или проездной?', tr: 'For one ride, or a travel pass?',
        words: [['одну', 'one'], ['поездку', 'ride'], ['или', 'or'], ['проездной', 'travel pass']] },
      { speaker: 'Traveler', side: 'right', ru: 'На одну поездку.', tr: 'For one ride.', words: [] },
      { speaker: 'Cashier', side: 'left', ru: 'С вас пятьдесят рублей.', tr: 'That will be fifty rubles.',
        words: [['С вас', 'from you (i.e. you owe)'], ['пятьдесят', 'fifty'], ['рублей', 'rubles']] },
    ],
  },
  'weather-smalltalk': {
    topicId: 'weather', title: 'Small Talk About Today’s Weather', sub: 'Friend · You (everyday chat)',
    lines: [
      { speaker: 'Friend', side: 'left', ru: 'Какая сегодня погода?', tr: 'What’s the weather like today?',
        words: [['Какая', 'what kind of'], ['погода', 'weather']] },
      { speaker: 'You', side: 'right', ru: 'Сегодня солнечно и тепло.', tr: 'It’s sunny and warm today.',
        words: [['солнечно', 'sunny'], ['тепло', 'warm']] },
      { speaker: 'Friend', side: 'left', ru: 'Правда? А на улице холодно?', tr: 'Really? Is it cold outside?',
        words: [['Правда', 'really'], ['холодно', 'cold']] },
      { speaker: 'You', side: 'right', ru: 'Нет, совсем не холодно. Очень приятно.', tr: 'No, not cold at all. It’s very pleasant.',
        words: [['совсем не', 'not at all'], ['приятно', 'pleasant']] },
      { speaker: 'Friend', side: 'left', ru: 'Отлично! Тогда пойдём гулять.', tr: 'Great! Then let’s go for a walk.',
        words: [['Отлично', 'great'], ['пойдём гулять', 'let’s go for a walk']] },
    ],
  },
  'weather-rain': {
    topicId: 'weather', title: 'Rain — Deciding Whether to Go Outside', sub: 'Friend · You (everyday chat)',
    lines: [
      { speaker: 'Friend', side: 'left', ru: 'Что будем делать сегодня?', tr: 'What are we going to do today?',
        words: [['будем делать', 'are going to do']] },
      { speaker: 'You', side: 'right', ru: 'Не знаю. Какая погода?', tr: 'I don’t know. What’s the weather like?',
        words: [['Не знаю', 'I don’t know']] },
      { speaker: 'Friend', side: 'left', ru: 'Идёт дождь.', tr: 'It’s raining.',
        words: [['Идёт дождь', 'it’s raining']] },
      { speaker: 'You', side: 'right', ru: 'Сильно?', tr: 'Heavily?',
        words: [['Сильно', 'heavily']] },
      { speaker: 'Friend', side: 'left', ru: 'Да, довольно сильно.', tr: 'Yes, quite heavily.',
        words: [['довольно', 'quite']] },
      { speaker: 'You', side: 'right', ru: 'Тогда возьмём зонты.', tr: 'Then we’ll take umbrellas.',
        words: [['возьмём', 'we’ll take'], ['зонты', 'umbrellas']] },
      { speaker: 'Friend', side: 'left', ru: 'Хорошая идея.', tr: 'Good idea.',
        words: [['Хорошая идея', 'good idea']] },
    ],
  },
  'weather-snow': {
    topicId: 'weather', title: 'Snow', sub: 'Friend · You (everyday chat)',
    lines: [
      { speaker: 'Friend', side: 'left', ru: 'На улице снег?', tr: 'Is there snow outside?',
        words: [['снег', 'snow']] },
      { speaker: 'You', side: 'right', ru: 'Да, идёт снег.', tr: 'Yes, it’s snowing.',
        words: [['идёт снег', 'it’s snowing']] },
      { speaker: 'Friend', side: 'left', ru: 'Сильно холодно?', tr: 'Is it very cold?',
        words: [['Сильно холодно', 'very cold']] },
      { speaker: 'You', side: 'right', ru: 'Да, очень холодно. Минус пять градусов.', tr: 'Yes, it’s very cold. Minus five degrees.',
        words: [['очень холодно', 'very cold'], ['Минус пять градусов', 'minus five degrees']] },
      { speaker: 'Friend', side: 'left', ru: 'Ого! Тогда нужно надеть тёплую куртку.', tr: 'Wow! Then I need to put on a warm jacket.',
        words: [['надеть', 'to put on'], ['тёплую куртку', 'warm jacket']] },
      { speaker: 'You', side: 'right', ru: 'И не забудь шарф!', tr: 'And don’t forget a scarf!',
        words: [['не забудь', 'don’t forget'], ['шарф', 'scarf']] },
    ],
  },
  'weather-temperature': {
    topicId: 'weather', title: 'Asking About the Temperature', sub: 'Friend · You (everyday chat)',
    lines: [
      { speaker: 'Friend', side: 'left', ru: 'Сколько сегодня градусов?', tr: 'How many degrees is it today?',
        words: [['Сколько', 'how many'], ['градусов', 'degrees']] },
      { speaker: 'You', side: 'right', ru: 'Около десяти градусов.', tr: 'About ten degrees.',
        words: [['Около', 'about'], ['десяти', 'ten']] },
      { speaker: 'Friend', side: 'left', ru: 'Плюс десять?', tr: 'Plus ten?',
        words: [['Плюс', 'plus']] },
      { speaker: 'You', side: 'right', ru: 'Да, плюс десять.', tr: 'Yes, plus ten.', words: [] },
      { speaker: 'Friend', side: 'left', ru: 'А ночью?', tr: 'And at night?',
        words: [['ночью', 'at night']] },
      { speaker: 'You', side: 'right', ru: 'Ночью будет около пяти градусов.', tr: 'At night it will be around five degrees.',
        words: [['будет', 'will be'], ['пяти', 'five']] },
    ],
  },
  'weather-wind': {
    topicId: 'weather', title: 'Wind', sub: 'Friend · You (everyday chat)',
    lines: [
      { speaker: 'Friend', side: 'left', ru: 'Сегодня холодно?', tr: 'Is it cold today?',
        words: [['холодно', 'cold']] },
      { speaker: 'You', side: 'right', ru: 'Не очень. Всего пять градусов.', tr: 'Not really. It’s only five degrees.',
        words: [['Не очень', 'not really'], ['Всего', 'only']] },
      { speaker: 'Friend', side: 'left', ru: 'Но очень ветрено.', tr: 'But it’s very windy.',
        words: [['ветрено', 'windy']] },
      { speaker: 'You', side: 'right', ru: 'Да, из-за ветра холоднее.', tr: 'Yes, because of the wind it feels colder.',
        words: [['из-за ветра', 'because of the wind'], ['холоднее', 'colder']] },
      { speaker: 'Friend', side: 'left', ru: 'Тогда лучше надеть куртку.', tr: 'Then it’s better to wear a jacket.',
        words: [['лучше', 'better'], ['надеть куртку', 'to wear a jacket']] },
    ],
  },
  'weather-cloudy': {
    topicId: 'weather', title: 'Cloudy Weather', sub: 'Friend · You (everyday chat)',
    lines: [
      { speaker: 'Friend', side: 'left', ru: 'Какая погода сегодня?', tr: 'What’s the weather like today?',
        words: [['погода', 'weather']] },
      { speaker: 'You', side: 'right', ru: 'Пасмурно и облачно.', tr: 'It’s overcast and cloudy.',
        words: [['Пасмурно', 'overcast'], ['облачно', 'cloudy']] },
      { speaker: 'Friend', side: 'left', ru: 'Солнца нет?', tr: 'There’s no sun?',
        words: [['Солнца нет', 'there’s no sun']] },
      { speaker: 'You', side: 'right', ru: 'Нет, сегодня солнца нет.', tr: 'No, there’s no sun today.',
        words: [['солнца нет', 'there’s no sun']] },
      { speaker: 'Friend', side: 'left', ru: 'Жаль.', tr: 'That’s a shame.',
        words: [['Жаль', 'that’s a shame']] },
      { speaker: 'You', side: 'right', ru: 'Но дождя пока нет.', tr: 'But it’s not raining yet.',
        words: [['дождя пока нет', 'no rain yet']] },
    ],
  },
  'weather-changing': {
    topicId: 'weather', title: 'The Weather Suddenly Changes', sub: 'Friend · You (everyday chat)',
    lines: [
      { speaker: 'Friend', side: 'left', ru: 'Какая погода! Только что шёл дождь.', tr: 'What weather! It was just raining.',
        words: [['Только что', 'just now'], ['шёл дождь', 'it was raining']] },
      { speaker: 'You', side: 'right', ru: 'А сейчас уже солнечно.', tr: 'And now it’s already sunny.',
        words: [['уже', 'already'], ['солнечно', 'sunny']] },
      { speaker: 'Friend', side: 'left', ru: 'Погода быстро меняется.', tr: 'The weather changes quickly.',
        words: [['быстро', 'quickly'], ['меняется', 'changes']] },
      { speaker: 'You', side: 'right', ru: 'Да, утром было пасмурно, а сейчас солнце.', tr: 'Yes, it was overcast in the morning, and now it’s sunny.',
        words: [['утром', 'in the morning'], ['было', 'was'], ['солнце', 'sun']] },
    ],
  },
  'weather-forecast': {
    topicId: 'weather', title: 'Checking the Weather Forecast', sub: 'Friend · You (everyday chat)',
    lines: [
      { speaker: 'Friend', side: 'left', ru: 'Какая погода будет завтра?', tr: 'What will the weather be like tomorrow?',
        words: [['завтра', 'tomorrow']] },
      { speaker: 'You', side: 'right', ru: 'Сейчас посмотрю.', tr: 'Let me check.',
        words: [['Сейчас посмотрю', 'let me check']] },
      { speaker: 'Friend', side: 'left', ru: 'Что показывает прогноз?', tr: 'What does the forecast say?',
        words: [['показывает', 'shows'], ['прогноз', 'forecast']] },
      { speaker: 'You', side: 'right', ru: 'Завтра будет холодно и дождливо.', tr: 'Tomorrow it will be cold and rainy.',
        words: [['дождливо', 'rainy']] },
      { speaker: 'Friend', side: 'left', ru: 'Весь день будет дождь?', tr: 'Will it rain all day?',
        words: [['Весь день', 'all day']] },
      { speaker: 'You', side: 'right', ru: 'Нет, только утром.', tr: 'No, only in the morning.',
        words: [['только утром', 'only in the morning']] },
      { speaker: 'Friend', side: 'left', ru: 'Тогда пойдём в музей утром, а погуляем после обеда.', tr: 'Then we’ll go to a museum in the morning and walk around after lunch.',
        words: [['музей', 'museum'], ['погуляем', 'we’ll walk around'], ['после обеда', 'after lunch']] },
    ],
  },
  'weather-what-to-wear': {
    topicId: 'weather', title: 'Deciding What to Wear', sub: 'Friend · You (everyday chat)',
    lines: [
      { speaker: 'Friend', side: 'left', ru: 'Что ты наденешь сегодня?', tr: 'What are you going to wear today?',
        words: [['наденешь', 'will you wear']] },
      { speaker: 'You', side: 'right', ru: 'Не знаю. Какая погода?', tr: 'I don’t know. What’s the weather like?',
        words: [['Не знаю', 'I don’t know']] },
      { speaker: 'Friend', side: 'left', ru: 'Прохладно и ветрено.', tr: 'It’s cool and windy.',
        words: [['Прохладно', 'cool']] },
      { speaker: 'You', side: 'right', ru: 'Тогда надену куртку и свитер.', tr: 'Then I’ll wear a jacket and a sweater.',
        words: [['надену', 'I’ll wear'], ['свитер', 'sweater']] },
      { speaker: 'Friend', side: 'left', ru: 'Возьми ещё шарф.', tr: 'Take a scarf too.',
        words: [['Возьми', 'take'], ['шарф', 'scarf']] },
      { speaker: 'You', side: 'right', ru: 'Хорошо.', tr: 'Okay.', words: [] },
    ],
  },
  'weather-yesterday-today': {
    topicId: 'weather', title: 'Yesterday vs. Today', sub: 'Friend · You (everyday chat)',
    lines: [
      { speaker: 'Friend', side: 'left', ru: 'Вчера было тепло?', tr: 'Was it warm yesterday?',
        words: [['Вчера', 'yesterday'], ['было', 'was']] },
      { speaker: 'You', side: 'right', ru: 'Да, вчера было очень тепло и солнечно.', tr: 'Yes, yesterday was very warm and sunny.',
        words: [['очень', 'very']] },
      { speaker: 'Friend', side: 'left', ru: 'А сегодня?', tr: 'And today?', words: [] },
      { speaker: 'You', side: 'right', ru: 'Сегодня холодно и пасмурно.', tr: 'Today it’s cold and overcast.', words: [] },
      { speaker: 'Friend', side: 'left', ru: 'Какая разница!', tr: 'What a difference!',
        words: [['разница', 'difference']] },
      { speaker: 'You', side: 'right', ru: 'Да, погода изменилась.', tr: 'Yeah, the weather changed.',
        words: [['изменилась', 'changed']] },
    ],
  },
  'weather-seasons': {
    topicId: 'weather', title: 'Talking About Seasons', sub: 'Friend · You (everyday chat)',
    lines: [
      { speaker: 'Friend', side: 'left', ru: 'Какое твоё любимое время года?', tr: 'What’s your favorite season?',
        words: [['время года', 'season']] },
      { speaker: 'You', side: 'right', ru: 'Мне нравится весна.', tr: 'I like spring.',
        words: [['нравится', 'I like'], ['весна', 'spring']] },
      { speaker: 'Friend', side: 'left', ru: 'Почему?', tr: 'Why?',
        words: [['Почему', 'why']] },
      { speaker: 'You', side: 'right', ru: 'Потому что весной становится теплее.', tr: 'Because it gets warmer in spring.',
        words: [['становится теплее', 'gets warmer']] },
      { speaker: 'Friend', side: 'left', ru: 'А зимой тебе нравится?', tr: 'Do you like winter?',
        words: [['зимой', 'in winter']] },
      { speaker: 'You', side: 'right', ru: 'Не очень. Зимой холодно и часто идёт снег.', tr: 'Not really. In winter it’s cold and it often snows.',
        words: [['часто', 'often']] },
    ],
  },
  'weather-asking-stranger': {
    topicId: 'weather', title: 'Asking a Stranger About the Weather', sub: 'Stranger · You (asking on the street)',
    lines: [
      { speaker: 'You', side: 'right', ru: 'Извините, вы не знаете, какая сегодня погода?', tr: 'Excuse me, do you know what the weather is like today?',
        words: [['Извините', 'excuse me'], ['вы не знаете', 'do you know']] },
      { speaker: 'Stranger', side: 'left', ru: 'Сегодня прохладно и немного ветрено.', tr: 'It’s cool and a little windy today.',
        words: [['немного', 'a little']] },
      { speaker: 'You', side: 'right', ru: 'А дождь будет?', tr: 'Will it rain?',
        words: [['дождь будет', 'will it rain']] },
      { speaker: 'Stranger', side: 'left', ru: 'Кажется, вечером будет дождь.', tr: 'It seems it will rain in the evening.',
        words: [['Кажется', 'it seems'], ['вечером', 'in the evening']] },
      { speaker: 'You', side: 'right', ru: 'Спасибо!', tr: 'Thank you!',
        words: [['Спасибо', 'thanks']] },
      { speaker: 'Stranger', side: 'left', ru: 'Пожалуйста.', tr: 'You’re welcome.',
        words: [['Пожалуйста', 'you’re welcome']] },
    ],
  },
  'opening-bank-card': {
    topicId: 'banksim', title: 'Opening a Bank Card', sub: 'Bank Employee · You (bank branch)',
    lines: [
      { speaker: 'You', side: 'right', ru: 'Здравствуйте. Я хочу открыть банковскую карту.', tr: 'Hello. I want to open a bank card.',
        words: [['Здравствуйте', 'hello (formal)'], ['хочу', 'I want'], ['открыть', 'to open'], ['банковскую', 'bank (adj.)'], ['карту', 'card']] },
      { speaker: 'Bank Employee', side: 'left', ru: 'Конечно. У вас есть паспорт?', tr: 'Of course. Do you have your passport?',
        words: [['Конечно', 'of course'], ['паспорт', 'passport']] },
      { speaker: 'You', side: 'right', ru: 'Да, вот мой паспорт.', tr: 'Yes, here is my passport.',
        words: [['вот', 'here is'], ['мой', 'my']] },
      { speaker: 'Bank Employee', side: 'left', ru: 'Вам нужна дебетовая карта?', tr: 'Do you need a debit card?',
        words: [['нужна', 'need'], ['дебетовая', 'debit']] },
      { speaker: 'You', side: 'right', ru: 'Да.', tr: 'Yes.', words: [] },
      { speaker: 'Bank Employee', side: 'left', ru: 'Укажите ваш номер телефона.', tr: 'Enter your phone number.',
        words: [['Укажите', 'enter/indicate'], ['номер', 'number'], ['телефона', 'phone']] },
      { speaker: 'You', side: 'right', ru: 'Хорошо.', tr: 'Okay.', words: [] },
      { speaker: 'You', side: 'right', ru: 'Сколько времени занимает оформление карты?', tr: 'How long does it take to issue the card?',
        words: [['Сколько времени', 'how long'], ['занимает', 'takes'], ['оформление', 'issuing']] },
      { speaker: 'Bank Employee', side: 'left', ru: 'Около десяти минут.', tr: 'About ten minutes.',
        words: [['Около', 'about'], ['десяти минут', 'ten minutes']] },
      { speaker: 'You', side: 'right', ru: 'Хорошо, спасибо.', tr: 'Okay, thank you.', words: [] },
    ],
  },
  'atm-withdraw': {
    topicId: 'banksim', title: 'Withdrawing Money from an ATM', sub: 'Staff · ATM · You',
    lines: [
      { speaker: 'You', side: 'right', ru: 'Извините, где здесь банкомат?', tr: 'Excuse me, where is the ATM?',
        words: [['Извините', 'excuse me'], ['где', 'where'], ['банкомат', 'ATM']] },
      { speaker: 'Staff', side: 'left', ru: 'Вон там, справа.', tr: 'Over there, on the right.',
        words: [['Вон там', 'over there'], ['справа', 'on the right']] },
      { speaker: 'You', side: 'right', ru: 'Спасибо.', tr: 'Thank you.', words: [] },
      { speaker: 'You', side: 'right', ru: 'Я хочу снять деньги.', tr: 'I want to withdraw money.',
        words: [['хочу', 'I want'], ['снять', 'to withdraw'], ['деньги', 'money']] },
      { speaker: 'ATM', side: 'left', ru: 'Введите PIN-код.', tr: 'Enter your PIN.',
        words: [['Введите', 'enter'], ['PIN-код', 'PIN code']] },
      { speaker: 'ATM', side: 'left', ru: 'Выберите сумму.', tr: 'Select the amount.',
        words: [['Выберите', 'select'], ['сумму', 'amount']] },
      { speaker: 'You', side: 'right', ru: 'Я хочу снять пять тысяч рублей.', tr: 'I want to withdraw 5,000 rubles.',
        words: [['пять тысяч', 'five thousand'], ['рублей', 'rubles']] },
      { speaker: 'ATM', side: 'left', ru: 'Получить чек?', tr: 'Would you like a receipt?',
        words: [['Получить', 'to get/receive'], ['чек', 'receipt']] },
      { speaker: 'You', side: 'right', ru: 'Да, пожалуйста.', tr: 'Yes, please.', words: [] },
    ],
  },
  'paying-card': {
    topicId: 'banksim', title: 'Paying by Card in a Shop', sub: 'Cashier · You',
    lines: [
      { speaker: 'Cashier', side: 'left', ru: 'С вас две тысячи рублей.', tr: 'That will be 2,000 rubles.',
        words: [['С вас', 'that will be/you owe'], ['две тысячи', 'two thousand'], ['рублей', 'rubles']] },
      { speaker: 'You', side: 'right', ru: 'Можно оплатить картой?', tr: 'Can I pay by card?',
        words: [['Можно', 'can/may'], ['оплатить', 'to pay'], ['картой', 'by card']] },
      { speaker: 'Cashier', side: 'left', ru: 'Да, конечно.', tr: 'Yes, of course.', words: [] },
      { speaker: 'You', side: 'right', ru: 'Хорошо.', tr: 'Okay.', words: [] },
      { speaker: 'Cashier', side: 'left', ru: 'Введите PIN-код.', tr: 'Enter your PIN.',
        words: [['Введите', 'enter'], ['PIN-код', 'PIN code']] },
      { speaker: 'Cashier', side: 'left', ru: 'Оплата прошла.', tr: 'The payment went through.',
        words: [['Оплата', 'payment'], ['прошла', 'went through']] },
      { speaker: 'You', side: 'right', ru: 'Спасибо.', tr: 'Thank you.', words: [] },
    ],
  },
  'buying-esim': {
    topicId: 'banksim', title: 'Buying a SIM/eSIM at the Airport', sub: 'Vendor · You (airport kiosk)',
    lines: [
      { speaker: 'You', side: 'right', ru: 'Здравствуйте. Я хочу купить SIM-карту.', tr: 'Hello. I want to buy a SIM card.',
        words: [['хочу', 'I want'], ['купить', 'to buy'], ['SIM-карту', 'SIM card']] },
      { speaker: 'Vendor', side: 'left', ru: 'Конечно. Вам нужна SIM-карта или eSIM?', tr: 'Of course. Do you need a physical SIM or an eSIM?',
        words: [['нужна', 'need'], ['или', 'or']] },
      { speaker: 'You', side: 'right', ru: 'eSIM, пожалуйста.', tr: 'An eSIM, please.', words: [] },
      { speaker: 'Vendor', side: 'left', ru: 'Какой тариф вам нужен?', tr: 'Which plan do you need?',
        words: [['Какой', 'which'], ['тариф', 'plan']] },
      { speaker: 'You', side: 'right', ru: 'Мне нужен интернет на десять дней.', tr: 'I need internet for ten days.',
        words: [['нужен', 'need'], ['интернет', 'internet'], ['на десять дней', 'for ten days']] },
      { speaker: 'Vendor', side: 'left', ru: 'Сколько гигабайт вам нужно?', tr: 'How many gigabytes do you need?',
        words: [['Сколько', 'how many'], ['гигабайт', 'gigabytes']] },
      { speaker: 'You', side: 'right', ru: 'Мне нужно много интернета.', tr: 'I need a lot of data.',
        words: [['много', 'a lot']] },
      { speaker: 'You', side: 'right', ru: 'У вас есть безлимитный интернет?', tr: 'Do you have unlimited internet?',
        words: [['есть', 'have/is there'], ['безлимитный', 'unlimited']] },
      { speaker: 'You', side: 'right', ru: 'Сколько это стоит?', tr: 'How much does it cost?',
        words: [['стоит', 'costs']] },
      { speaker: 'You', side: 'right', ru: 'Хорошо, беру.', tr: 'Okay, I’ll take it.',
        words: [['беру', 'I’ll take']] },
    ],
  },
  'activating-esim': {
    topicId: 'banksim', title: 'Activating the eSIM', sub: 'Vendor · You (airport kiosk)',
    lines: [
      { speaker: 'Vendor', side: 'left', ru: 'Отсканируйте этот QR-код.', tr: 'Scan this QR code.',
        words: [['Отсканируйте', 'scan'], ['этот', 'this'], ['QR-код', 'QR code']] },
      { speaker: 'You', side: 'right', ru: 'Хорошо.', tr: 'Okay.', words: [] },
      { speaker: 'You', side: 'right', ru: 'Мне нужно что-нибудь настроить на телефоне?', tr: 'Do I need to configure anything on my phone?',
        words: [['нужно', 'need'], ['настроить', 'to configure'], ['телефоне', 'phone']] },
      { speaker: 'Vendor', side: 'left', ru: 'Да, включите мобильный интернет.', tr: 'Yes, turn on mobile data.',
        words: [['включите', 'turn on'], ['мобильный интернет', 'mobile data']] },
      { speaker: 'You', side: 'right', ru: 'А этот номер будет работать сразу?', tr: 'And will this number work immediately?',
        words: [['номер', 'number'], ['будет работать', 'will work'], ['сразу', 'immediately']] },
      { speaker: 'Vendor', side: 'left', ru: 'Да.', tr: 'Yes.', words: [] },
      { speaker: 'You', side: 'right', ru: 'Интернет уже работает?', tr: 'Is the internet working now?',
        words: [['уже', 'already/now'], ['работает', 'is working']] },
      { speaker: 'Vendor', side: 'left', ru: 'Да.', tr: 'Yes.', words: [] },
      { speaker: 'You', side: 'right', ru: 'Отлично, спасибо!', tr: 'Great, thank you!',
        words: [['Отлично', 'great']] },
    ],
  },
  'airport-wifi': {
    topicId: 'banksim', title: 'Airport Wi-Fi', sub: 'Staff · You',
    lines: [
      { speaker: 'You', side: 'right', ru: 'Извините, здесь есть бесплатный Wi-Fi?', tr: 'Excuse me, is there free Wi‑Fi here?',
        words: [['есть', 'is there'], ['бесплатный', 'free']] },
      { speaker: 'Staff', side: 'left', ru: 'Да.', tr: 'Yes.', words: [] },
      { speaker: 'You', side: 'right', ru: 'Как подключиться к Wi-Fi?', tr: 'How do I connect to the Wi‑Fi?',
        words: [['Как', 'how'], ['подключиться', 'to connect']] },
      { speaker: 'Staff', side: 'left', ru: 'Выберите сеть Pulkovo Free Wi-Fi.', tr: 'Select the Pulkovo Free Wi‑Fi network.',
        words: [['Выберите', 'select'], ['сеть', 'network']] },
      { speaker: 'You', side: 'right', ru: 'Нужен пароль?', tr: 'Do I need a password?',
        words: [['Нужен', 'need'], ['пароль', 'password']] },
      { speaker: 'Staff', side: 'left', ru: 'Нет, не нужен.', tr: 'No, you don’t.', words: [] },
      { speaker: 'You', side: 'right', ru: 'Спасибо.', tr: 'Thank you.', words: [] },
    ],
  },
  'internet-not-working': {
    topicId: 'banksim', title: 'Internet Is Not Working', sub: 'Staff · You',
    lines: [
      { speaker: 'You', side: 'right', ru: 'Извините, у меня не работает интернет.', tr: 'Excuse me, my internet isn’t working.',
        words: [['не работает', 'isn’t working']] },
      { speaker: 'Staff', side: 'left', ru: 'Что именно не работает?', tr: 'What exactly isn’t working?',
        words: [['именно', 'exactly']] },
      { speaker: 'You', side: 'right', ru: 'Мобильный интернет не работает.', tr: 'Mobile data isn’t working.',
        words: [['Мобильный', 'mobile']] },
      { speaker: 'Staff', side: 'left', ru: 'Перезагрузите телефон.', tr: 'Restart your phone.',
        words: [['Перезагрузите', 'restart']] },
      { speaker: 'You', side: 'right', ru: 'Я уже перезагрузила телефон, но интернет всё равно не работает.', tr: 'I’ve already restarted my phone, but the internet still isn’t working.',
        words: [['уже', 'already'], ['перезагрузила', 'restarted'], ['всё равно', 'still/anyway']] },
      { speaker: 'Staff', side: 'left', ru: 'Давайте проверим настройки.', tr: 'Let’s check the settings.',
        words: [['проверим', 'let’s check'], ['настройки', 'settings']] },
      { speaker: 'You', side: 'right', ru: 'Хорошо.', tr: 'Okay.', words: [] },
    ],
  },
  'airport-checkin': {
    topicId: 'airport', title: 'Check-In', sub: 'Airline Staff · You',
    lines: [
      { speaker: 'Airline Staff', side: 'left', ru: 'Здравствуйте. Ваш паспорт, пожалуйста.', tr: 'Hello. Your passport, please.',
        words: [['Ваш', 'your'], ['паспорт', 'passport'], ['пожалуйста', 'please']] },
      { speaker: 'You', side: 'right', ru: 'Здравствуйте. Вот мой паспорт.', tr: 'Hello. Here is my passport.',
        words: [['Вот', 'here is'], ['мой', 'my']] },
      { speaker: 'Airline Staff', side: 'left', ru: 'Куда вы летите?', tr: 'Where are you flying to?',
        words: [['Куда', 'where (to)'], ['летите', 'are flying']] },
      { speaker: 'You', side: 'right', ru: 'Я лечу в Санкт-Петербург.', tr: 'I’m flying to Saint Petersburg.',
        words: [['лечу', 'I’m flying'], ['Санкт-Петербург', 'Saint Petersburg']] },
      { speaker: 'Airline Staff', side: 'left', ru: 'У вас есть багаж?', tr: 'Do you have any luggage?',
        words: [['багаж', 'luggage']] },
      { speaker: 'You', side: 'right', ru: 'Да, у меня есть один чемодан.', tr: 'Yes, I have one suitcase.',
        words: [['один', 'one'], ['чемодан', 'suitcase']] },
      { speaker: 'Airline Staff', side: 'left', ru: 'Хотите выбрать место?', tr: 'Would you like to choose a seat?',
        words: [['Хотите', 'would you like'], ['выбрать', 'to choose'], ['место', 'seat']] },
      { speaker: 'You', side: 'right', ru: 'Да, можно место у окна?', tr: 'Yes, could I have a window seat?',
        words: [['окна', 'window']] },
    ],
  },
  'airport-finding-gate': {
    topicId: 'airport', title: 'Finding Your Gate', sub: 'Airline Staff · You',
    lines: [
      { speaker: 'You', side: 'right', ru: 'Извините, где мой выход?', tr: 'Excuse me, where is my gate?',
        words: [['Извините', 'excuse me'], ['где', 'where'], ['выход', 'gate/exit']] },
      { speaker: 'Airline Staff', side: 'left', ru: 'Выход номер десять.', tr: 'Gate number ten.',
        words: [['номер', 'number'], ['десять', 'ten']] },
      { speaker: 'You', side: 'right', ru: 'А где выход номер десять?', tr: 'And where is gate number ten?', words: [] },
      { speaker: 'Airline Staff', side: 'left', ru: 'Идите прямо, потом направо.', tr: 'Go straight, then right.',
        words: [['Идите', 'go'], ['прямо', 'straight'], ['потом', 'then'], ['направо', 'right']] },
    ],
  },
  'airport-passport-control': {
    topicId: 'airport', title: 'Passport Control', sub: 'Border Officer · You',
    lines: [
      { speaker: 'Border Officer', side: 'left', ru: 'Ваш паспорт, пожалуйста.', tr: 'Your passport, please.',
        words: [['Ваш', 'your'], ['паспорт', 'passport']] },
      { speaker: 'You', side: 'right', ru: 'Вот мой паспорт.', tr: 'Here is my passport.', words: [['Вот', 'here is'], ['мой', 'my']] },
      { speaker: 'Border Officer', side: 'left', ru: 'Какова цель вашей поездки?', tr: 'What is the purpose of your trip?',
        words: [['Какова', 'what is'], ['цель', 'purpose'], ['поездки', 'trip']] },
      { speaker: 'You', side: 'right', ru: 'Туризм.', tr: 'Tourism.', words: [['Туризм', 'tourism']] },
      { speaker: 'Border Officer', side: 'left', ru: 'Сколько дней вы будете в России?', tr: 'How many days will you be in Russia?',
        words: [['Сколько', 'how many'], ['дней', 'days'], ['России', 'Russia']] },
      { speaker: 'You', side: 'right', ru: 'Девять дней.', tr: 'Nine days.', words: [['Девять', 'nine'], ['дней', 'days']] },
      { speaker: 'Border Officer', side: 'left', ru: 'Где вы будете жить?', tr: 'Where will you be staying?',
        words: [['Где', 'where'], ['будете жить', 'will you be staying']] },
      { speaker: 'You', side: 'right', ru: 'В Санкт-Петербурге, в отеле.', tr: 'In Saint Petersburg, at a hotel.',
        words: [['отеле', 'hotel']] },
      { speaker: 'Border Officer', side: 'left', ru: 'У вас есть обратный билет?', tr: 'Do you have a return ticket?',
        words: [['обратный', 'return'], ['билет', 'ticket']] },
      { speaker: 'You', side: 'right', ru: 'Да, вот мой билет.', tr: 'Yes, here is my ticket.', words: [['билет', 'ticket']] },
    ],
  },
  'airport-security-check': {
    topicId: 'airport', title: 'Security Check', sub: 'Security Officer · You',
    lines: [
      { speaker: 'Security Officer', side: 'left', ru: 'Поставьте сумку сюда, пожалуйста.', tr: 'Please put your bag here.',
        words: [['Поставьте', 'put'], ['сумку', 'bag'], ['сюда', 'here']] },
      { speaker: 'You', side: 'right', ru: 'Хорошо.', tr: 'Okay.', words: [] },
      { speaker: 'Security Officer', side: 'left', ru: 'Снимите куртку, пожалуйста.', tr: 'Please take off your jacket.',
        words: [['Снимите', 'take off'], ['куртку', 'jacket']] },
      { speaker: 'You', side: 'right', ru: 'Хорошо.', tr: 'Okay.', words: [] },
      { speaker: 'Security Officer', side: 'left', ru: 'У вас есть ноутбук?', tr: 'Do you have a laptop?',
        words: [['ноутбук', 'laptop']] },
      { speaker: 'You', side: 'right', ru: 'Да, вот он.', tr: 'Yes, here it is.', words: [['вот он', 'here it is']] },
    ],
  },
};

export const INITIAL_FLASHCARDS = [
  { word: 'капучино', tr: 'cappuccino', dialogId: 'coffee-formal', topicId: 'cafes' },
  { word: 'пожалуйста', tr: 'please', dialogId: 'coffee-formal', topicId: 'cafes' },
  { word: 'билет', tr: 'ticket', dialogId: 'buying-ticket', topicId: 'metro' },
  { word: 'счёт', tr: 'bill', dialogId: 'asking-bill', topicId: 'cafes' },
  { word: 'сырники', tr: 'cheese pancakes (syrniki)', dialogId: 'breakfast-formal', topicId: 'cafes' },
  { word: 'омлет', tr: 'omelet', dialogId: 'breakfast-formal', topicId: 'cafes' },
  { word: 'каша', tr: 'porridge', dialogId: 'breakfast-formal', topicId: 'cafes' },
  { word: 'сметаной', tr: 'sour cream', dialogId: 'breakfast-casual', topicId: 'cafes' },
];
